name: Next.js CI/CD

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}, .next/cache
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}-nextjs-${{ hashFiles('**/next.config.js') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Build Next.js
      run: pnpm run build

    - name: Deploy to GitHub Pages
      run: |
        echo "DEPLOY_URL=https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY/" >> $GITHUB_ENV
        echo "COMMIT_MSG=chore: deploy to GitHub Pages at commit $GITHUB_SHA" >> $GITHUB_ENV
        echo "GIT_EMAIL=$GITHUB_ACTOR@users.noreply.github.com" >> $GITHUB_ENV
        echo "GIT_USER=$GITHUB_ACTOR" >> $GITHUB_ENV
        echo "BUILD_DIR=out" >> $GITHUB_ENV

        git init
        git config user.name "$GIT_USER"
        git config user.email "$GIT_EMAIL"
        git remote add origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git checkout -b gh-pages
        git add -A
        git commit -m "$COMMIT_MSG"
        git push origin gh-pages --force
